image: node:12

cache:
  paths:
    - node_modules/

stages:
  - test
  - deploy

lint-and-test:
  stage: test
  script:
    - yarn install
    - yarn build
    - yarn test
    - yarn lint

# Deploy docs to Gitlab pages
# pages:
#   stage: deploy
#   only:
#     - master
#   script:
#     - yarn install
#     - yarn docs
#     - mv docs public
#   artifacts:
#     paths:
#       - public
