name: Lint and test

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nodejs: [10, 12, 14]

    steps:
    - uses: actions/checkout@v2

    # https://github.com/actions/setup-node
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'

    - run: yarn install
    - run: yarn lint
    - run: yarn test
    - run: yarn build
